#!/usr/bin/env perl 
#Addison's quick tmux multiplexor script, written by T. Addison Leake.  Licensed under the GPL 2. Vers.1
use warnings;
use strict;

use FindBin;
use lib $FindBin::Bin;

use Params;

my %options = Params::GetParams();

my $hostref =  $options{'hosts'};
my @hosts = @$hostref;
my $window = '';

while (<STDIN>){
	my @temp = split(" ", $_);
	for (@temp){
		push(@hosts, $_);
	}
}

sub FindWindow {
	my $windowmass = `tmux list-windows`;
	my @splitwin =  split (/\n/, $windowmass);
	for (@splitwin){
		if (m/(active)/){
			my @a = split(/:/, $_);
			$window = $a[0];
			print "window = $window\n";
		}
	}
}

sub MakePanes  {			
	my $i = 0;
	my $remote_user = '';
	if ($options{'user'}){
		$remote_user = "-l $options{'user'}"
	}
	for (@hosts){
		print `tmux split-window -t $window -d "ssh $remote_user $hosts[$i]"`;
		print `tmux select-layout -t $window tiled`;
		$i++;
	}
	print `tmux set-window-option synchronize-panes on`;
	print `tmux break-pane -t 0`;
	print `tmux select-layout -t $window tiled`
	
}


FindWindow();
MakePanes();
